import Head from "next/head";
import Navbar from "@/components/Navbar";
import Blog from "@/components/Blog";
import LatestPosts from "@/components/LatestPosts";
import PopularPosts from "@/components/PopularPosts";
import CategoryPosts from "@/components/CategoryPosts";
import CTA from "@/components/CTA";
import { Typography } from "@mui/material";
import Footer from "@/components/Footer";
import FeaturedBlog from "@/components/FeaturedPost";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section id="featured">
          <FeaturedBlog />
        </section>
        <section id="latest">
          <LatestPosts />
        </section>
        <section id="popular">
          <PopularPosts />
        </section>
        <section id="category">
          <CategoryPosts />
        </section>
        <Footer />
      </main>
    </>
  );
}
